name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Generate SVG and GIF (transparent + no white dots)
        uses: Platane/snk@v3
        with:
          github_user_name: rahmoundif
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
          palette: github-dark
          color_snake: "#00FFAA"
          color_dots: "#00000000,#00000000,#00000000,#00000000,#00000000"

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
