name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation SVG + GIF
      - name: Generate SVG and GIF
        uses: Platane/snk@v3
        with:
          github_user_name: rahmoundif
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
            palette: github-dark  # 👈 fond clair et transparent
          color_snake: "#00FFAA" # (optionnel) couleur du snake
          color_dots: "#dcdcdc,#c0c0c0,#808080,#404040,#202020" # (optionnel)

      # Deploy to GitHub Pages
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
